image: docker:git

stages:
  - deploy

deploy_ui_to_staging:
  stage: deploy
  environment: Development
  services:
       - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.com:5005
    - docker build --build-arg NPM_TOKEN=6f3bcf35-125d-40da-bfab-dcfb6efece79 -t registry.gitlab.com/reallybigtree/pinecone-facebook-destination .
    - docker push registry.gitlab.com/reallybigtree/pinecone-facebook-destination
  only:
    - develop
